### ISSUE TITLE
annotate DARs for each cell type

### ISSUE THREAD

**Issue by linhch5** [p4rkerw/Muto_Wilson_NComm_2020#3]
Hi, Dr. Wilson and Dr. Muto:
Thank you very much for providing your code to working with the snATAC-seq analysis. The following error appeared when I was using your code to annotate the cell type specific DAR. Do you know why and how can I solve the problem?

list.peakAnno <- lapply(list.dar.gr, annotatePeak, TxDb = txdb,tssRegion = c(-3000, 3000), verbose = FALSE)
**Error in which(strand(subject) != "-") :  argument to 'which' is not logical**
![1621005341(1)](https://user-images.githubusercontent.com/68565460/118295168-2a755900-b4a1-11eb-96f5-b8c255633807.png)

**Comment by p4rkerw** [comment]
Hello,

Thanks for checking out our repo! It’s hard to know exactly what the problem is without a reproducible example but I have a few ideas for you to try out. I think the issue is that the strand variable in your granges object is set to “*” instead of “+” or “-“. That might throw an error like the one you’re describing. Try changing the strand variable for all the data to “+” and run the function again. You might also want to check out the chipseekr website for additional info. 

Parker

**Comment by p4rkerw** [comment]
.
